name: unit-tests
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Unit Tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: go test ./...